name: Compile Arduino UNO R4 WiFi Examples
on:
  push:
    paths:
      - ".github/workflows/buildExamples.yml"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/buildExamples.yml"
      - "examples/**"
      - "src/**"

  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:renesas_uno:unor4wifi
            platforms: |
              - name: arduino:renesas_uno

    steps:        
      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
        
      - name: Install Ethernet
        run: arduino-cli lib install Ethernet

      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
          sketch-paths: |
            - examples
          sketches: |
            # Include all sketches in examples directory
            - examples/**/*.ino
            # Exclude specific sketches from compilation
            - exclude:examples/**/SAMD_WiFiManager.ino
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      # - name: Compile examples
      #   uses: arduino/compile-sketches@v1
      #   with:
      #     fqbn: ${{ matrix.board.fqbn }}
      #     platforms: ${{ matrix.board.platforms }}
      #     libraries: |
      #       # Install the library from the local path.
      #       - source-path: ./
      #     sketch-paths: |
      #       - examples
      #     enable-deltas-report: true
      #     sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
