name: Compile Arduino UNO R4 WiFi Examples
on:
  push:
    paths:
      - ".github/workflows/buildExamples.yml"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/buildExamples.yml"
      - "examples/**"
      - "src/**"

  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:renesas_uno:unor4wifi
            platforms: |
              - name: arduino:renesas_uno

    steps:        
      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
        
      - name: Install Ethernet
        run: arduino-cli lib install Ethernet

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find relevant examples
        id: find-examples
        run: |
          EXCLUDED=$(echo "$EXCLUDE_EXAMPLES" | tr ' ' '|')
          EXAMPLES=$(find examples -name "*.ino" | grep -vE "$EXCLUDED" || echo "")
          echo "examples_list<<EOF" >> $GITHUB_OUTPUT
          echo "$EXAMPLES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "📋 Examples to compile:"
          echo "$EXAMPLES"

      - name: Compile selected examples
        if: steps.find-examples.outputs.examples_list != ''
        run: |
          for sketch in ${{ steps.find-examples.outputs.examples_list }}; do
            echo "🔨 Compiling $sketch"
            arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi $sketch
          done

      # - name: Compile examples
      #   uses: arduino/compile-sketches@v1
      #   with:
      #     fqbn: ${{ matrix.board.fqbn }}
      #     platforms: ${{ matrix.board.platforms }}
      #     libraries: |
      #       # Install the library from the local path.
      #       - source-path: ./
      #     sketch-paths: |
      #       - examples
      #     enable-deltas-report: true
      #     sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
